disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - function_body_length
  - cyclomatic_complexity
  - trailing_comma

opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string
  - conditional_returns_on_newline
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - fatal_error_message
  - file_name
  - first_where
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - modifier_order
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - redundant_type_annotation
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# configurable rules
indentation_width:
  indentation_width: 2
  include_comments: false

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 300
  error: 500

nesting:
  type_level: 3

# paths to ignore during linting
excluded:
  - Pods
  - AIChat.xcodeproj
  - AIChat/Preview Content

# reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
